baseURL = "https://zavestudios.com/"
languageCode = "en-us"
title = " "
contentDir = "docs"
theme = "hugo-theme-relearn"

[params]
  themeVariant = "blue"
  disableTitleSeparator = true
  collapsibleMenu = true
  alwaysopen = false
  [params.logo]
    src = "/images/logo.png"

[[params.customCSS]]
  href = "/css/custom.css"

[module]
  [[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"
  [[module.imports]]
    path = "github.com/zavestudios/panchito"
    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/applications/panchito.md"
  [[module.imports]]
    path = "github.com/zavestudios/rigoberta"
    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/applications/rigoberta.md"
  [[module.imports]]
    path = "github.com/zavestudios/thehouseguy"
    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/applications/thehouseguy.md"
  [[module.imports]]
    path = "github.com/zavestudios/xavierlopez.me"
    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/applications/xavierlopez-me.md"
  [[module.imports]]
    path = "github.com/zavestudios/platform-pipelines"
    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/platform-services/platform-pipelines.md"
  [[module.imports]]
    path = "github.com/zavestudios/pg"
    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/experiments/multi-tenant-databasing.md"
  [[module.imports]]
    path = "github.com/zavestudios/kubernetes-platform-infrastructure"
    [[module.imports.mounts]]
      source = "docs"
      target = "content/infrastructure/kubernetes-platform-infrastructure"
  [[module.imports]]
    path = "gitlab.com/platformystical/bigbang"
    [[module.imports.mounts]]
      source = "docs"
      target = "assets/platform-services/bigbang"
