baseURL = "https://zavestudios.com/"
languageCode = "en-us"
title = " "
contentDir = "docs"
theme = "hugo-theme-relearn"

[params]
  themeVariant = "blue"
  disableTitleSeparator = true
  collapsibleMenu = true
  alwaysopen = false
  [params.logo]
    src = "/images/logo.png"

[[params.customCSS]]
  href = "/css/custom.css"

[module]
  [[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"
